### ISSUE TITLE
How to stop service?

### ISSUE THREAD

**Issue by telmedola** [ppicas/flutter-android-background#13]
In my application, if user logoff, i need to stop service background.

**Comment by telmedola** [comment]
I found

**Comment by bobosette** [comment]
@telmedola how did you stop the service?

**Comment by telmedola** [comment]
@bobosette In configureFlutterEngine override method, call stopService passing the intent that started in startService. Example in kotlin: 
if (method.method == "stopService") {
                    stopService(Intent(this@MainActivity, BackgroundService::class.java))
                    result.success("stop")
}

**Comment by bobosette** [comment]
Thank you

Il Gio 2 Dic 2021, 14:36 telmedola ***@***.***> ha scritto:
