### ISSUE TITLE
Flutter updated v2 embedding changes doesnt work!!

### ISSUE THREAD

**Issue by ExypnosDevloper** [ppicas/flutter-android-background#5]
We have tested the project with your configuration, it works. But when we were integrating with our sample app which is being developed with the v2, it was not getting inside LifecycleDetetctor.kt and that's why it was not able to analyze ActivityLifeCyclecallbacks() and it wasn't working. If you have updated the application then please share the updates. Also, your guidance would be appreciatable

**Comment by ppicas** [comment]
Hi @ExypnosDevloper I updated the repo making the project compatible with v2. This should solve your problem :)
