### ISSUE TITLE
[QUESTION] Run background task without persistent notification

### ISSUE THREAD

**Issue by vinceramcesoliveros** [ppicas/flutter-android-background#7]
I tried to delete any method that involves notification. suddenly, it gives error whenever I run the flutter project.
Is it possible to remove persistent notification?

**Comment by elias8** [comment]
No. In order to keep the app in the foreground even if the user is not interacting with it, and you still want to keep the app running, you must show a notification. For more check out the android doc [here](https://developer.android.com/guide/components/services#Types-of-services).
