### ISSUE TITLE
I can not call method Cannel in Bakcground

### ISSUE THREAD

**Issue by adsizmusa** [ppicas/flutter-android-background#8]
I have methods in MainActivity. IIt is working in this method When my app is open. but When my app closed it is not working.
![image](https://user-images.githubusercontent.com/56891037/116755724-88bb2a00-aa13-11eb-96f5-f6bdba0026e5.png)

I have take this error "No implementation found for method"

also Some plugins do not worked in background

**Comment by ppicas** [comment]
This is probably because you also have to register the `MethodChannel` when the service is started, since it's a different instance of `FlutterEngine`. For instance you could register you `MethodChannel` inside this block https://github.com/ppicas/flutter-android-background/blob/fcb520ad89ef6199cd8c5f6a01f98e541b9c39d4/android/app/src/main/kotlin/com/example/background/BackgroundService.kt#L60.

**Comment by adsizmusa** [comment]
Thank you very much for your answer. It is working . I need another properties . I use a "context" , like this 

How do I  create "context" properties

`   private fun startFlutterNativeView() {
        if (flutterEngine != null) return

        Log.i("BackgroundService", "Starting FlutterEngine")

        getCallbackRawHandle()?.let { callbackRawHandle ->
            flutterEngine = FlutterEngine(this).also { engine ->
                val callbackInformation =
                        FlutterCallbackInformation.lookupCallbackInformation(callbackRawHandle)


                engine.dartExecutor.executeDartCallback(
                        DartExecutor.DartCallback(
                                assets,
                                FlutterMain.findAppBundlePath(),
                                callbackInformation
                        )
                );

                val binaryMessenger = engine.dartExecutor.binaryMessenger;
                MethodChannel(binaryMessenger, "com.arge24/call_direct").apply {
                    setMethodCallHandler { call, result ->
                        else if (call.method.equals("callNumber")) {
                        PhoneCall phoneCall = new PhoneCall();
                        String number = call . argument ("number");
                        phoneCall.makeCall(context, number);
                    } else if (call.method.equals("callEmd")) {
                        PhoneCall phoneCall = new PhoneCall();
                        phoneCall.makeCallEnd(context);
                    } else if (call.method.equals("acceptRingingCall")) {
                        PhoneCall phoneCall = new PhoneCall();
                        phoneCall.makeAcceptRingingCall(context);
                    } else {
                        result.notImplemented();
                    }
                    }
                }
            }
        }
    }`
